# Generated by Django 4.2.19 on 2025-02-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
